# Generated by Django 5.2 on 2025-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_request_blood_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_blood',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
