# Generated by Django 5.2.5 on 2025-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_request_blood_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_blood',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
