# Generated by Django 5.2 on 2025-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donor_user_alter_donor_address_alter_donor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
