# Generated by Django 5.2.5 on 2025-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donor_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='hospital',
            field=models.CharField(blank=True, choices=[('Goa Medical College Blood Bank', 'Goa Medical College Blood Bank'), ('Manipal Hospital Blood Bank', 'Manipal Hospital Blood Bank'), ('Hospicio Hospital Blood Bank', 'Hospicio Hospital Blood Bank'), ('Asilo Hospital Blood Bank', 'Asilo Hospital Blood Bank'), ('District Hospital Blood Bank', 'District Hospital Blood Bank'), ('Red Cross Blood Bank', 'Red Cross Blood Bank'), ('Sub District Hospital Blood Bank', 'Sub District Hospital Blood Bank'), ('Vrundavan Hospital Blood Bank', 'Vrundavan Hospital Blood Bank'), ('Apollo Victor Hospital Blood Bank', 'Apollo Victor Hospital Blood Bank'), ('Shri Sai Central Blood Bank & Lab', 'Shri Sai Central Blood Bank & Lab'), ('Fonsecas Pathology Laboratory / Blood Bank', 'Fonsecas Pathology Laboratory / Blood Bank'), ('Jeevandhara Blood Bank', 'Jeevandhara Blood Bank')], max_length=100, null=True),
        ),
    ]
