# Generated by Django 5.2.5 on 2025-10-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donor_phone_number'),
        ('donors', '0005_donor_hospital'),
    ]

    operations = [
    ]
