# Generated by Django 5.2 on 2025-10-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Registration',
        ),
    ]
